import Head from 'next/head';
import Link from 'next/link';
import {useRouter} from 'next/router';
import {useDispatch} from 'react-redux';
import SEO from '@/components/seo';
import Wrapper from '@/layout/wrapper';
import HeaderFour from '@/layout/headers/header-4';
import FooterTwo from '@/layout/footers/footer-2';
import {add_cart_product,initialOrderQuantity} from '@/redux/features/cartSlice';

const products={
  'collar-amalfi':{_id:'jolie-collar-amalfi',slug:'collar-amalfi',title:'Collar Amalfi',category:'Collares',price:89000,quantity:20,img:'/assets/img/instagram/4/instagram-1.jpg',description:'Un collar delicado pensado para sumar un detalle especial a tus looks de todos los días.'},
  'aros-soleil':{_id:'jolie-aros-soleil',slug:'aros-soleil',title:'Aros Soleil',category:'Aros',price:65000,quantity:20,img:'/assets/img/instagram/4/instagram-3.jpg',description:'Aros femeninos y versátiles para acompañarte con un toque de luz y personalidad.'},
  'pulsera-marina':{_id:'jolie-pulsera-marina',slug:'pulsera-marina',title:'Pulsera Marina',category:'Pulseras',price:75000,quantity:20,img:'/assets/img/instagram/4/instagram-4.jpg',description:'Una pulsera delicada y alegre, ideal para combinar y expresar tu esencia.'},
  'tobillera-serena':{_id:'jolie-tobillera-serena',slug:'tobillera-serena',title:'Tobillera Serena',category:'Tobilleras',price:69000,quantity:20,img:'/assets/img/instagram/4/instagram-6.jpg',description:'Una tobillera sutil para sumar un detalle femenino y especial.'},
  'collar-coral':{_id:'jolie-collar-coral',slug:'collar-coral',title:'Collar Coral',category:'Collares',price:95000,quantity:20,img:'/assets/img/slider/4/slider-1.png',description:'Una pieza Jolie con personalidad, pensada para destacar sin perder delicadeza.'},
  'aros-estrella':{_id:'jolie-aros-estrella',slug:'aros-estrella',title:'Aros Estrella',category:'Aros',price:72000,quantity:20,img:'/assets/img/instagram/4/instagram-3.jpg',description:'Aros con carácter delicado para iluminar tus momentos.'},
  'pulsera-capri':{_id:'jolie-pulsera-capri',slug:'pulsera-capri',title:'Pulsera Capri',category:'Pulseras',price:79000,quantity:20,img:'/assets/img/instagram/4/instagram-4.jpg',description:'Color, detalle y estilo en una pieza ideal para usar sola o combinada.'},
  'collar-oceana':{_id:'jolie-collar-oceana',slug:'collar-oceana',title:'Collar Oceana',category:'Collares',price:99000,quantity:20,img:'/assets/img/instagram/4/instagram-1.jpg',description:'Un collar elegante y fresco inspirado en esos detalles que hacen único tu estilo.'},
  'collar-aurora':{_id:'jolie-collar-aurora',slug:'collar-aurora',title:'Collar Aurora',category:'Collares',price:105000,quantity:20,img:'/assets/img/instagram/4/instagram-6.jpg',description:'Una pieza especial para acompañarte de día o de noche.'},
  'aros-luna':{_id:'jolie-aros-luna',slug:'aros-luna',title:'Aros Luna',category:'Aros',price:68000,quantity:20,img:'/assets/img/instagram/4/instagram-3.jpg',description:'Diseño delicado, femenino y fácil de combinar.'},
  'pulsera-esencia':{_id:'jolie-pulsera-esencia',slug:'pulsera-esencia',title:'Pulsera Esencia',category:'Pulseras',price:82000,quantity:20,img:'/assets/img/instagram/4/instagram-4.jpg',description:'Una pulsera pensada para recordarte que tu esencia es tu mejor joya.'},
  'tobillera-mar':{_id:'jolie-tobillera-mar',slug:'tobillera-mar',title:'Tobillera Mar',category:'Tobilleras',price:74000,quantity:20,img:'/assets/img/instagram/4/instagram-1.jpg',description:'Una tobillera ligera y femenina para acompañar tus días.'}
};

export default function ProductPDP(){
  const router=useRouter(); const dispatch=useDispatch(); const product=products[router.query.slug];
  if(!product) return <Wrapper><HeaderFour/><main className="jpdp-empty"><h1>Producto no encontrado</h1><Link href="/shop">Volver a la tienda</Link></main><FooterTwo/></Wrapper>;
  const add=()=>{dispatch(initialOrderQuantity());dispatch(add_cart_product(product));router.push('/cart')};
  const wa=`https://wa.me/595986934997?text=${encodeURIComponent('Hola Jolie, quiero consultar por '+product.title)}`;
  return <Wrapper><SEO pageTitle={`${product.title} | Jolie Jewelry`} description={`${product.title} de Jolie Jewelry. Bonita y Única.`}/><Head><style>{`.jpdp{background:#fffaf7;color:#5f3b30;padding:62px 0 82px}.jpdp-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:64px;align-items:center}.jpdp-media{background:#f7ebe5;border-radius:18px;overflow:hidden}.jpdp-media img{display:block;width:100%;aspect-ratio:1/1.08;object-fit:cover}.jpdp-kicker{font-size:10px;letter-spacing:.16em;text-transform:uppercase;color:#a48b81;margin-bottom:12px}.jpdp h1{font:400 clamp(42px,5vw,64px)/1.02 'Playfair Display',serif;margin:0 0 16px}.jpdp-price{font-size:20px;font-weight:600;color:#c98268;margin-bottom:24px}.jpdp-copy{font-size:14px;line-height:1.8;color:#806a63;max-width:540px;margin-bottom:28px}.jpdp-benefits{display:grid;gap:10px;font-size:12px;color:#7b655c;margin-bottom:28px}.jpdp-actions{display:flex;gap:12px;flex-wrap:wrap}.jpdp-cart,.jpdp-wa,.jpdp-back{padding:15px 22px;border-radius:8px;font-size:10px;font-weight:600;text-transform:uppercase;text-align:center}.jpdp-cart{border:0;background:#c98268;color:#fff}.jpdp-wa{border:1px solid #c98268;color:#c98268}.jpdp-back{color:#7b655c}.jpdp-trust{margin-top:35px;padding-top:24px;border-top:1px solid #ead6ce;display:grid;grid-template-columns:repeat(3,1fr);gap:14px;font-size:10px;color:#8f766c}.jpdp-trust div{background:#fff;padding:14px;border-radius:10px;text-align:center}.jpdp-empty{min-height:50vh;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:18px;background:#fffaf7;color:#5f3b30}@media(max-width:767px){.jpdp{padding:30px 0 55px}.jpdp-grid{grid-template-columns:1fr;gap:28px}.jpdp h1{font-size:39px}.jpdp-actions{display:grid}.jpdp-trust{grid-template-columns:1fr 1fr}.jpdp-trust div:last-child{grid-column:1/-1}}`}</style></Head><HeaderFour/><main className="jpdp"><div className="container"><div className="jpdp-grid"><div className="jpdp-media"><img src={product.img} alt={product.title}/></div><div><div className="jpdp-kicker">{product.category} · Jolie Jewelry</div><h1>{product.title}</h1><div className="jpdp-price">Gs. {product.price.toLocaleString('es-PY')}</div><p className="jpdp-copy">{product.description}</p><div className="jpdp-benefits"><span>♡ Selección cuidada</span><span>✦ Packaging especial</span><span>🚚 Envíos a todo Paraguay</span></div><div className="jpdp-actions"><button className="jpdp-cart" onClick={add}>Agregar al carrito</button><a className="jpdp-wa" href={wa} target="_blank" rel="noreferrer">Consultar por WhatsApp</a><Link className="jpdp-back" href="/shop">Seguir viendo joyas</Link></div><div className="jpdp-trust"><div>Bonita y Única</div><div>Atención personalizada</div><div>Compra con confianza</div></div></div></div></div></main><FooterTwo/></Wrapper>;
}